package zte.phone.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "PhoneNoteTable".
 */
public class PhoneNote {

    private Long bmob_phone_id;
    private String phone_name;
    private Integer phone_number;
    private String project_name;
    private String phone_time;
    private String phone_photo_url;

    public PhoneNote() {
    }

    public PhoneNote(Long bmob_phone_id, String phone_name, Integer phone_number, String project_name, String phone_time, String phone_photo_url) {
        this.bmob_phone_id = bmob_phone_id;
        this.phone_name = phone_name;
        this.phone_number = phone_number;
        this.project_name = project_name;
        this.phone_time = phone_time;
        this.phone_photo_url = phone_photo_url;
    }

    public Long getBmob_phone_id() {
        return bmob_phone_id;
    }

    public void setBmob_phone_id(Long bmob_phone_id) {
        this.bmob_phone_id = bmob_phone_id;
    }

    public String getPhone_name() {
        return phone_name;
    }

    public void setPhone_name(String phone_name) {
        this.phone_name = phone_name;
    }

    public Integer getPhone_number() {
        return phone_number;
    }

    public void setPhone_number(Integer phone_number) {
        this.phone_number = phone_number;
    }

    public String getProject_name() {
        return project_name;
    }

    public void setProject_name(String project_name) {
        this.project_name = project_name;
    }

    public String getPhone_time() {
        return phone_time;
    }

    public void setPhone_time(String phone_time) {
        this.phone_time = phone_time;
    }

    public String getPhone_photo_url() {
        return phone_photo_url;
    }

    public void setPhone_photo_url(String phone_photo_url) {
        this.phone_photo_url = phone_photo_url;
    }

}
